server: 
  port: 80

spring:
  application:
    name: weixin-gzh-server
  datasource:  
    #url: jdbc:mysql://120.78.134.230:3306/mysql?useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=utf-8
    username: root
    password: zaq12WSX@

